import os

from from_root import from_root

PROJECT_ROOT = from_root()

ENV_MODE = os.environ["ENV_MODE"]
OPENROUTER_API_KEY = os.environ["OPENROUTER_API_KEY"]
OPENROUTER_BASE_URL = os.environ["OPENROUTER_BASE_URL"]
OPENROUTER_MODEL = os.environ["OPENROUTER_MODEL"]

MODEL_MAX_COMPLETION_TOKENS = 512

__all__ = [
    "PROJECT_ROOT",
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_MODEL",
    "MODEL_MAX_COMPLETION_TOKENS",
]
